apiVersion: v1
kind: Pod
metadata:
  name: springapp
  labels:
    app: spring
spec:
  containers:
  - name: springcontainer
    image: gajjala7012/spring-boot-mongo:latest
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springsvc
spec:
  type: NodePort
  selector:
    app: spring
  ports:
  - port: 80
    targetPort: 8080
